/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/mXChSz4MiCa
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function EpubForm() {
  return (
    <main className="flex min-h-screen w-full items-center justify-center bg-gray-100 px-4 py-12 dark:bg-gray-950">
      <div className="w-full max-w-md space-y-4">
        <h1 className="text-3xl font-bold tracking-tighter text-gray-900 dark:text-gray-50">Convert to EPUB</h1>
        <p className="text-gray-500 dark:text-gray-400">Enter a URL to convert the web page to an EPUB file.</p>
        <form className="flex w-full space-x-2">
          <Input className="flex-1" placeholder="Enter URL" required type="url" />
          <Button type="submit">Convert</Button>
        </form>
      </div>
    </main>
  )
}
